//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WindowsProject1.rc
//
#define IDC_MYICON                      2
#define IDD_WINDOWSPROJECT1_DIALOG      102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_WINDOWSPROJECT1             107
#define IDI_SMALL                       108
#define IDC_WINDOWSPROJECT1             109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOGADD                   129
#define IDD_DIALOGSELECTFILE            130
#define IDD_DIALOGSELL                  131
#define IDD_DIALOGMODIFY                132
#define IDD_DIALOGMODIFYNEW             133
#define IDD_DIALOGSEARCH                134
#define IDD_DIALOGSEARCHSHOW            135
#define IDD_DIALOGTJ                    136
#define IDD_DIALOG2                     137
#define IDD_DIALOGPRESENT               137
#define IDD_DIALOGTIMESH                138
#define IDC_EDIT1                       1003
#define IDC_BUTTON1                     1004
#define IDC_EDITTIME                    1005
#define IDOK2                           1007
#define IDCANCELE                       1008
#define IDC_EDITSFILE                   1009
#define IDC_BUTTONSFILE                 1010
#define IDC_BUTTON2                     1023
#define IDC_EDITMODEL                   1026
#define IDC_EDITMANU                    1027
#define IDC_EDITUPRICE                  1028
#define IDC_EDITNUM                     1029
#define IDC_EDITCUSTOMER                1030
#define IDC_EDITACCESSORY               1031
#define IDC_EDITTIMES                   1032
#define IDC_EDITACCESSORYS              1033
#define IDC_EDITMODELS                  1034
#define IDC_EDITMANUS                   1035
#define IDC_EDITUPRICES                 1036
#define IDC_EDITNUMS                    1037
#define IDC_EDITCUSTOMERS               1038
#define IDC_BUTTONS                     1039
#define IDOK2S                          1040
#define IDCANCELES                      1041
#define IDC_RADIOSPF                    1042
#define IDC_RADIOSLSH                   1043
#define IDC_EDITMQ                      1045
#define IDOKM                           1046
#define IDCANCELM                       1047
#define IDC_BUTTONMQ                    1048
#define IDC_EDITMS                      1049
#define IDC_EDITTIMEMN                  1050
#define IDC_EDITACCESSORYMN             1051
#define IDC_EDITMODELMN                 1052
#define IDC_EDITMANUMN                  1053
#define IDC_EDITUPRICEMN                1054
#define IDC_EDITNUMMN                   1055
#define IDC_EDITCUSTOMERMN              1056
#define IDC_BUTTONMNSAVE                1057
#define IDOK2MN                         1058
#define IDCANCELEMN                     1059
#define IDC_RADIOSPFMN                  1060
#define IDC_RADIOSLSHMN                 1061
#define IDC_RADIOJINHUOMN               1062
#define IDC_RADIOPJSCH                  1063
#define IDC_RADIOGHSHSCH                1064
#define IDC_RADIOCUSTSCH                1065
#define IDC_EDITSEARCH                  1066
#define IDC_BUTTONQDSEARCH              1067
#define IDOKSCH                         1068
#define IDCANCELESCH                    1069
#define IDC_EDITSS                      1070
#define IDOKSS                          1071
#define IDCANCELESS                     1072
#define IDC_EDITPROFIT                  1073
#define IDC_EDITTJIVENTORYRP            1074
#define IDOKTJ                          1075
#define IDC_EDITTJTURNOVER              1076
#define IDC_EDITPRESENT2                1077
#define IDC_EDITPRESENT3                1078
#define IDC_BUTTONPRE3                  1079
#define IDC_EDITPRESENT1                1080
#define IDOKPRESENT                     1081
#define IDC_BUTTONPRE1                  1082
#define IDC_BUTTONPRE2                  1083
#define IDC_EDITDAYSTART                1084
#define IDC_EDITHOURSTART               1085
#define IDC_EDITMINSTART                1086
#define IDC_EDITMONTHEND                1087
#define IDC_EDITDAYEND                  1088
#define IDC_EDITHOUREND                 1089
#define IDC_EDIT8                       1090
#define IDC_EDITMINEND                  1090
#define IDC_EDITMONTHSTART              1092
#define IDC_BUTTONTJQD                  1093
#define IDC_EDITTIMESH                  1094
#define IDOKTIMESH                      1095
#define IDC_BUTTONDQ                    1096
#define IDC_EDITDQ                      1097
#define IDC_EDITADDDAY                  1098
#define IDC_EDITADDHOUR                 1099
#define IDC_EDITADDMIN                  1100
#define IDC_EDITADDMONTH                1101
#define IDC_EDITSELLDAY                 1102
#define IDC_EDITSELLHOUR                1103
#define IDC_EDIT4                       1104
#define IDC_EDITSELLMIN                 1104
#define IDC_EDITSELLMONTH               1105
#define IDC_EDITPRESENTINFO             1106
#define File                            32771
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
